* gnetlist -g spice-sdb --nomunge -o eg1.mod eg1.sch
*********************************************************
* Spice file generated by gnetlist                      *
* spice-sdb version 4.28.2007 by SDB --                 *
* provides advanced spice netlisting capability.        *
* Documentation at http://www.brorson.com/gEDA/SPICE/   *
*********************************************************
*==============  Begin SPICE netlist of main design ============
Vsupply 0 2 DC 10V
R1 0 2 1k  
.print dc v(2)
.dc > eg1.dat
.end
